kbuild: deb-pkg: supply headers necessary for scripts
By default kernel supplies build scripts for the host arch.

This makes modules unbuildable on the target arch. To make module builds
available, one can rebuild scripts, but necessary includes are missing:

```
ivan@rockpro64:~$ sudo make -C /lib/modules/4.19.28-cloudflare-2019.3.4-2-gcbef1e9/build scripts
make: Entering directory '/usr/src/linux-headers-4.19.28-cloudflare-2019.3.4-2-gcbef1e9'
  HOSTCC  scripts/selinux/genheaders/genheaders
scripts/selinux/genheaders/genheaders.c:19:22: fatal error: classmap.h: No such file or directory
 #include "classmap.h"
                      ^
compilation terminated.
scripts/Makefile.host:90: recipe for target 'scripts/selinux/genheaders/genheaders' failed
make[3]: *** [scripts/selinux/genheaders/genheaders] Error 1
scripts/Makefile.build:544: recipe for target 'scripts/selinux/genheaders' failed
make[2]: *** [scripts/selinux/genheaders] Error 2
scripts/Makefile.build:544: recipe for target 'scripts/selinux' failed
make[1]: *** [scripts/selinux] Error 2
Makefile:1062: recipe for target 'scripts' failed
make: *** [scripts] Error 2
make: Leaving directory '/usr/src/linux-headers-4.19.28-cloudflare-2019.3.4-2-gcbef1e9'
```

After adding selinux includes, tools includes are missing:

```
ivan@rockpro64:~$ sudo make -C /lib/modules/4.19.28-cloudflare-2019.3.4-2-gcbef1e9/build scripts
make: Entering directory '/usr/src/linux-headers-4.19.28-cloudflare-2019.3.4-2-gcbef1e9'
  HOSTCC  scripts/selinux/genheaders/genheaders
  HOSTCC  scripts/selinux/mdp/mdp
  HOSTCC  scripts/bin2c
  HOSTCC  scripts/kallsyms
  HOSTCC  scripts/conmakehash
  HOSTCC  scripts/recordmcount
  HOSTCC  scripts/sortextable
scripts/sortextable.c:31:32: fatal error: tools/be_byteshift.h: No such file or directory
 #include <tools/be_byteshift.h>
                                ^
compilation terminated.
scripts/Makefile.host:90: recipe for target 'scripts/sortextable' failed
make[1]: *** [scripts/sortextable] Error 1
Makefile:1062: recipe for target 'scripts' failed
make: *** [scripts] Error 2
make: Leaving directory '/usr/src/linux-headers-4.19.28-cloudflare-2019.3.4-2-gcbef1e9'
```

After that scripts rebuild successfully.