rust: do not fail on stabilized features
We don't want to fail the build due to these:

```
error: the feature `let_else` has been stable since 1.65.0 and no longer requires an attribute to enable
   --> /build/linux-source/rust/alloc/lib.rs:166:12
    |
166 | #![feature(let_else)]
    |            ^^^^^^^^
    |
    = note: `-D stable-features` implied by `-D warnings`
```

Signed-off-by: Ivan Babrou <github@ivan.computer>